// This is a button with HTML code automatically generated by BTCPayJungle when I created a store.
// It was then transformed into JSX by https://transform.tools/html-to-jsx
// However, it's important to note that this does use dangerouslySetInnerHTML which opens the site up to XSS attacks
// But honestly I don't care anymore and 

import { useEffect } from "react"

const rawHTML = `
<style type="text/css"> .btcpay-form { display: inline-flex; align-items: center; justify-content: center; } .btcpay-form--inline { flex-direction: row; } .btcpay-form--block { flex-direction: column; } .btcpay-form--inline .submit { margin-left: 15px; } .btcpay-form--block select { margin-bottom: 10px; } .btcpay-form .btcpay-custom-container{ text-align: center; }.btcpay-custom { display: flex; align-items: center; justify-content: center; } .btcpay-form .plus-minus { cursor:pointer; font-size:25px; line-height: 25px; background: #DFE0E1; height: 30px; width: 45px; border:none; border-radius: 60px; margin: auto 5px; display: inline-flex; justify-content: center; } .btcpay-form select { -moz-appearance: none; -webkit-appearance: none; appearance: none; color: currentColor; background: transparent; border:1px solid transparent; display: block; padding: 1px; margin-left: auto; margin-right: auto; font-size: 11px; cursor: pointer; } .btcpay-form select:hover { border-color: #ccc; } #btcpay-input-price { -moz-appearance: none; -webkit-appearance: none; border: none; box-shadow: none; text-align: center; font-size: 25px; margin: auto; border-radius: 5px; line-height: 35px; background: #fff; } #btcpay-input-price::-webkit-outer-spin-button, #btcpay-input-price::-webkit-inner-spin-button { -webkit-appearance: none; margin: 0; } </style>
<form method="POST"  action="https://btcpayjungle.com/api/v1/invoices" class="btcpay-form btcpay-form--block">
  <input type="hidden" name="storeId" value="DbS43ooRL76QvbJm1foB3gGmgrjyEXedNyYBsggVrJ2F" />
  <input type="hidden" name="price" value="10" />
  <input type="hidden" name="currency" value="USD" />
<button type="submit" class="submit" name="submit" style="min-width:146px; min-height:40px; border-radius: 4px;border-style: none;background-color: #0f3b21;" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor"><span style="color:#fff">Pay with</span>
<img src="https://raw.githubusercontent.com/roslinpl/bitcoin.it-promotional_graphics/master/bitcoinLogo.svg" style="height:40px;display:inline-block;padding: 5% 0 5% 5px;vertical-align: middle;">
</button></form>
`

export const BitcoinButton = props => (
    <div>
        <div dangerouslySetInnerHTML={{__html: rawHTML}}></div>
      </div>
  )
  